Remove unused message format for `Performance/OpenStruct`
This PR suppresses the following warning.

```console
% path/to/rubocop-performance
% bundle exec rake

(snip)

/Users/koic/src/github.com/rubocop-hq/rubocop-performance/lib/rubocop/cop/performance/open_struct.rb:40:
warning: too many arguments for format string
```